Update get

diff --git a/bin/.local/bin/get b/bin/.local/bin/get
--- a/bin/.local/bin/get
+++ b/bin/.local/bin/get
@@ -1,6 +1,8 @@
 #!/bin/sh
 
 pkgs="$@"
+installer="echo "error: something went wrong" ; exit 1"
+
 check() {
   return command -v xbps-install >dev/null 2>&1
 }
@@ -11,6 +13,13 @@ elif check pacman; then
   installer="sudo pacman -Syu"
 elif check apt; then
   installer="sudo apt install -y"
+elif check dnf; then
+  installer="sudo dnf install -y"
+elif check brew; then
+  installer="brew install"
 else
-  echo Could not find package manager.
+  echo "error: could not find package manager." ; exit 1
 fi
+
+$installer $pkgs && echo "done." && exit 0
+exit 1
